# path to seeds sheet (TSV format, columns: seed, protein_id, ...)
seed: config/seeds.tsv

# path to taxonomic id to search seeds in (TSV format, columns: TaxId, NCBIGroups)
taxid: config/taxid.tsv

# name of the project 
project_name: your_name_project

# path to the result folder
output_folder: results

# e value threshold to use for psiblast (and blast as default is not in seeds.tsv)
e_val: 0.000001

# Option for ncbi_download_genome

ndg_option:
    # Values for section : {refseq,genbank}
    section: genbank
    # Values for assembly_levels : ['all', 'complete', 'chromosome', 'scaffold', 'contig']
    assembly_levels: all
    # Values for refseq_categories : {'reference', 'all'}
    refseq_categories: all
    # Values for groups : ['all', 'archaea', 'bacteria', 'fungi', 'invertebrate', 'metagenomes', 'plant', 'protozoa', 'vertebrate_mammalian', 'vertebrate_other', 'viral']
    # Will be used if none is give in base_set_taxid.tsv
    groups: all

speedup: False