$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  seed:
    type: string
  taxid:
    type: string
  project_name:
    type: string
  output_folder:
    type: string

  default_psiblast_option:
    type: object
    e_val:
      type: number
    required:
      - e_val
      
  default_blast_option:
    type: object
    e_val:
      type: number
    pid:
      type: number
    cov:
      type: number
    required:
      - e_val
      - pid
      - cov

  ndg_option:
    type: object
    properties:
      section:
        type: string
      assembly_levels:
        type: string
      refseq_categories:
        type: string
      groups:
        type: string
    required:
      - section
      - assembly_levels
      - refseq_categories

  speedup:
    type: boolean

  default_values_plot:
    type: object
    properties:
      color: string

required:
  - seed
  - taxid
  - project_name
  - output_folder
  - default_psiblast_option
  - default_blast_option
  - ndg_option
  - speedup