# path to seeds sheet (TSV format, columns: seed, protein_id, ...)
seed: .test/config/seeds.tsv

# path to taxonomic id to search seeds in (TSV format, columns: TaxId, NCBIGroups)
taxid: .test/config/taxid.tsv

# Path to personal database, it consists of a fasta file with all the proteins you want to add to the search: (TSV format, columns: protein_id, genome_id[, genome_name])
perso_database: ''

# Path to personal database annoation tsv file if fasta headers are not in the format: "sequence_name--genome_id description"
perso_annotation: ''

# name of the project 
project_name: your_project_name

# path to the result folder
output_folder: results

# e value threshold to use for psiblast (and blast as default is not in seeds.tsv)
default_psiblast_option:
    # E-value threshold
    psiblast_e_val: 0.01
    # Iteration 
    iteration: 3

# Blast option if not given in seeds.tsv
default_blast_option:
    # E-value threshold
    e_val: 0.0001
    # Percentage of identity threshold
    pid: 0.35
    # Coverage of the query treshold
    cov: 0.8

# Option for the Taxonomy DB parser
# If you want to update the Taxonomy dump, :warning: it increase the running time of the workflow
update_db: False

# Option for ncbi_download_genome
ndg_option:
    # Values for section : {'refseq','genbank'}
    section: refseq
    # Values for assembly_levels : ['all', 'complete', 'chromosome', 'scaffold', 'contig']
    assembly_levels: all
    # Values for refseq_categories : {'reference', 'all'}
    refseq_categories: all
    # Values for groups : ['all', 'archaea', 'bacteria', 'fungi', 'invertebrate', 'metagenomes', 'plant', 'protozoa', 'vertebrate_mammalian', 'vertebrate_other', 'viral']
    # Will be used if none is give in base_set_taxid.tsv
    groups: all

# Speedup the blast all vs all by adding a psiblast step to reduce dataset
speedup: True

# Default value for plot
default_values_plot:
    # Color
    color: '#131516' # This color is a dark grey similar to black
    # Turn color of the border a darker shade infer from the background if True else set the color to black
    colored_border: True
    # Turn border to roundish shape
    round_border: False

# If you only want the plot need a table (TSV format, columns: gene1, gene2..., index: genome_ids)
PAtab_table: results/plots/PAtab_table.tsv
