__default__:
    account   : lagard # your hpc account
    qos       : lagard # the qos namr
    time      : 60 # default time (minutes)
    nodes     : 1
    ntasks    : 1
    cpus      : 1
    mem       : 4gb # default memory
    output    : "{config['__output_folder__']}/logs/slurm/{rule}/{rule}.{wildcards}.out"
    error     : "{config['__output_folder__']}/logs/slurm/{rule}/{rule}.{wildcards}.err"
    name      : "JOBNAME.{rule}.{wildcards}",
