$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  seed:
    type: string
  taxid:
    type: string
  perso_database:
    type: string
  perso_annotation:
    type: string
  project_name:
    type: string
  output_folder:
    type: string

  default_psiblast_options:
    type: object
    properties:
      psiblast_e_val:
        type: number
        minimum: 0
        maximum: 1        
      iteration:
        type: number
        minimum: 1
        maximum: 5

  default_hmmsearch_options:
    type: object
    properties:
      focus: 
        type: string
        enum: ["domain","full"]
      e_val:
        type: number
        minimum: 0
        maximum: 1
    required:
      - e_val
      - focus

  hmm_profiles:
    type: string

  default_blast_options:
    type: object
    properties:
      e_val:
        type: number
        minimum: 0
        maximum: 1
      pid:
        type: number
        minimum: 0
        maximum: 1        
      cov:
        type: number
        minimum: 0
        maximum: 1
    required:
      - e_val
      - pid
      - cov

  silix_options:
    type: object
    properties:
      cov_min:
        type: string
        enum: ["mean","subject", "query", "shortest", "longest"]
      pid_min:
        type: string
        enum: ["mean","subject", "query", "shortest", "longest", "HSP"]
      length_min:
        type: number
    required:
      - cov_min
      - pid_min
      - length_min

  update_db:
    type: boolean

  ndg_options:
    type: object
    properties:
      section:
        type: string
        enum: ["refseq","genbank"]
      assembly_levels:
        type: string
        enum: ["all", "complete", "chromosome", "scaffold", "contig"]
      refseq_categories:
        type: string
        enum: ["reference", "all"]
      groups:
        type: string
        enum: ["all", "archaea", "bacteria", "fungi", "invertebrate", "metagenomes", "plant", "protozoa", "vertebrate_mammalian", "vertebrate_other", "viral"]
    required:
      - section
      - assembly_levels
      - refseq_categories

  speedup:
    type: boolean

  default_values_plot:
    type: object
    properties:
      color: 
        type: string
      colored_border:
        type: boolean
      round_border:
        type: boolean
        
  PAtab_table:
    type: string

required:
  - seed
  - project_name
  - output_folder
  - default_psiblast_options
  - default_blast_options
  - ndg_options
  - silix_options
  - speedup
  - default_values_plot
  - default_hmmsearch_options
  - hmm_profiles